### ISSUE TITLE
Encrypted Realm unable to open in Windows

### ISSUE THREAD

**Issue by q-amir** [realm/realm-studio#1581] opened 2023-05-11 06:53 UTC
**Describe the bug**
Unable to open encrypted realm on Windows

**To Reproduce**
1. Open Realm Studio on Windows with version 14.03 / 14.02
2. Open any encrypted realm file
3. Enter the encryption key
4. And you will see the same error as the screenshot below

**Expected behavior**
I should be able to see all my data in the realm db. It's work well on my macbook but not on my windows pc

**Screenshots**
![image](https://github.com/realm/realm-studio/assets/65205785/af96a316-647b-41d4-961f-6b603f7d7efb)

**Versions:**
 - OS:Windows
 - Studio Version 14.03 / 14.02

**Comment by kneth** [comment] 2023-05-11 09:34
@q-amir Thank you for reporting.

It is possible for you to test using node.js on Windows using a simple script:

```js
const key = new Int8Array([ /* your key */  ] );
let realm = new Realm({ path: "name-of-your-realm-file", encryptionKey: key });
console.log(`Schema: ${realm.schema.length}`);
realm.close();
```

**Comment by kneth** [comment] 2023-05-11 10:45
@q-amir Another question: was the encrypted Realm file created on a non-Windows platform?

**Comment by q-amir** [comment] 2023-05-12 01:26
> @q-amir Another question: was the encrypted Realm file created on a non-Windows platform?

@kneth Yes. I generate it by using Jenkins in my macbook

> @q-amir Thank you for reporting.
> 
> It is possible for you to test using node.js on Windows using a simple script:
> 
> ```js
> const key = new Int8Array([ /* your key */  ] );
> let realm = new Realm({ path: "name-of-your-realm-file", encryptionKey: key });
> console.log(`Schema: ${realm.schema.length}`);
> realm.close();
> ```

I will try this. let you know.

**Comment by q-amir** [comment] 2023-05-12 08:41
> @q-amir Thank you for reporting.
> 
> It is possible for you to test using node.js on Windows using a simple script:
> 
> ```js
> const key = new Int8Array([ /* your key */  ] );
> let realm = new Realm({ path: "name-of-your-realm-file", encryptionKey: key });
> console.log(`Schema: ${realm.schema.length}`);
> realm.close();
> ```

@kneth I just run the simple script and it's failed. 
Here is the error msg
`Failed to open the Realm: Error [RealmError]: Failed to open Realm file at path 'D:\Projects\Tests\TestMasterdata\chmd.realm': Realm file decryption failed (Decryption failed)`

**Comment by kneth** [comment] 2023-05-12 08:41
It might be a duplicate of #1373. Encrypted Realm file might be slightly dependent on the platform where they are created. My little script above will tell us if it is the case.

We have an [open issue](https://github.com/realm/realm-core/issues/3499) to fix it.

**Comment by q-amir** [comment] 2023-05-12 09:05
> It might be a duplicate of #1373. Encrypted Realm file might be slightly dependent on the platform where they are created. My little script above will tell us if it is the case.
> 
> We have an [open issue](https://github.com/realm/realm-core/issues/3499) to fix it.

@kneth I see. seems like I need to wait for an update. Is there any other way for me to make my realm db more secure?

**Comment by kneth** [comment] 2023-05-12 11:04
> Is there any other way for me to make my realm db more secure?

Our encryption is pretty good - the issue is how to share it across platforms. 

Most operating systems today offer encryption of the file system, which is a good option for the case the device is lost. It is a more general remark unrelated to Realm :smile:

**Comment by kneth** [comment] 2023-07-14 12:35
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.

**Closed as completed by kneth** 2023-07-14 12:35 UTC
Labels: O-Community
