### ISSUE TITLE
Can't delete multiple objects only one each time

### ISSUE THREAD

**Issue by Evyasafmordechai** [realm/realm-studio#968] opened 2018-10-25 07:39 UTC
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Versions:**
 - OS: [e.g. Mac/Windows/]
 - Studio Version [e.g. 2.0.0]
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**

**Comment by nirinchev** [comment] 2018-10-25 07:51
Duplicate of https://github.com/realm/realm-studio/issues/960.

**Closed by nirinchev** 2018-10-25 07:51 UTC
Labels: O:User
