### ISSUE TITLE
Realm Studio 3.12 is required but not release.

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-studio#1325] opened 2020-09-11 00:29 UTC
**Is your feature request related to a problem? Please describe.**
Realm Cocoa just released 5.4.0, which required Realm Studio 3.12 to open the database. But there is no Realm Studio 3.12 released.

**Describe the solution you'd like**
Release 3.12 ASAP.

**Describe alternatives you've considered**
Hold to not upgrade to Realm Cocoa 5.4.0.

**Additional context**
No.

**Comment by kraenhansen** [comment] 2020-09-11 09:56
@owenzhao expect a release in the beginning of the coming week.

**Comment by byrneciaran** [comment] 2020-09-18 16:15
> @owenzhao expect a release in the beginning of the coming week.

Hey @kraenhansen any update on a time for this release?

**Comment by kraenhansen** [comment] 2020-09-18 21:17
@owenzhao, @byrneciaran Since the latest version of Realm JS (and the underlying Realm Core) includes a file format version upgrade, users making use of Realm Studio to open database files directly off their simulator or device might be negatively impacted if we released a new version of Realm Studio before all SDKs have published a version using the new file format.

That being said, we're actively working on getting this released and [the PR upgrading Realm JS](https://github.com/realm/realm-studio/pull/1331) has now been merged into our master branch. If you want to try it out before it's released, you can clone this repository and run:

```bash
npm ci
npm run build
npx electron .
```

**Comment by tmtrademarked** [comment] 2020-09-18 21:24
Thanks, @kraenhansen! I appreciate the clarity here - but I just want to point out that there is also a negative impact to users who upgraded to the new version of the Realm Java library in this case where we *don't* have a version of Realm Studio that is compatible with the new file format. So there's definitely a chicken and egg problem here no matter which order you folks end up releasing things in. :-)

Similarly, I also really appreciate you providing the workaround so we can give the new version a try! Many thanks.

**Comment by joaodematejr** [comment] 2020-09-18 22:08
1+

**Comment by owenzhao** [comment] 2020-09-18 23:22
> @owenzhao, @byrneciaran Since the latest version of Realm JS (and the underlying Realm Core) includes a file format version upgrade, users making use of Realm Studio to open database files directly off their simulator or device might be negatively impacted if we released a new version of Realm Studio before all SDKs have published a version using the new file format.
> 
> That being said, we're actively working on getting this released and [the PR upgrading Realm JS](https://github.com/realm/realm-studio/pull/1331) has now been merged into our master branch. If you want to try it out before it's released, you can clone this repository and run:
> 
> ```shell
> npm ci
> npm run build
> npx electron .
> ```
> 
> My updated ETA on a release of this, is the beginning of the coming week.

I don't get the point. Your reply seems imply that Realm Studio 3.12 will only support the new file format and drop the previous all versions. In my option, it should support all versions including the new format. So there won't be the bad impact at all. Can you confirm your idea that only the new format is supported in Realm Studio 3.12?

**Comment by joaodematejr** [comment] 2020-09-19 04:16
+1

**Comment by byrneciaran** [comment] 2020-09-19 09:38
Thanks @kraenhansen, I can confirm this build opens v11 file format using Realm Xamarin :)

**Comment by kraenhansen** [comment] 2020-09-19 10:01
@owenzhao the upcoming release of Studio can upgrade files and open any Realm DB file that a previous version could. The breaking behavior is if your workflow includes opening that same file in a simulator or device which has not had it's SDK upgraded yet. In that case a new latest release of Realm Studio would break your workflow and potentially force you to upgrade your SDK to continue working. That happened for a couple of users when we released v3.11.0 and we would like to avoid that happening again.

That being said, we plan on releasing this the same way we've ended up releasing v3.11.0 (which uses file format v10), it is the version you get if you download Studio from our website or docs, but users of v3.10.0 (which used file format v9) won't be prompted to automatically upgrade (at least not right away), to limit any negative experience from the above-mentioned situation.

I understand the need to get a version of Realm Studio compatible with the latest SDKs released ASAP and want you to know that it's one of our top most priorities.

**Comment by owenzhao** [comment] 2020-09-19 10:16
> @owenzhao the upcoming release of Studio can upgrade files and open any Realm DB file that a previous version could. The breaking behavior is if your workflow includes opening that same file in a simulator or device which has not had it's SDK upgraded yet. In that case a new latest release of Realm Studio would break your workflow and potentially force you to upgrade your SDK to continue working. That happened for a couple of users when we released v3.11.0 and we would like to avoid that happening again.
> 
> That being said, we plan on releasing this the same way we've ended up releasing v3.11.0 (which uses file format v10), it is the version you get if you download Studio from our website or docs, but users of v3.10.0 (which used file format v9) won't be prompted to automatically upgrade (at least not right away), to limit any negative experience from the above-mentioned situation.
> 
> I understand the need to get a version of Realm Studio compatible with the latest SDKs released ASAP and want you to know that it's one of our top most priorities.

I got it. This seems to me like a bug. Realm Studio should be able to open and save the database in the original version of the target Realm database. But in fact, Realm Studio can open the previous versions of the Realm but can only save them in the latest format of Realm. That is the reason why you want to wait. 

But only waiting will never really fix this issue. Realm Studio should not change the original format of the target Realm file at the first place.

**Comment by kraenhansen** [comment] 2020-09-19 11:39
> I got it. This seems to me like a bug. Realm Studio should be able to open and save the database in the original version of the target Realm database. But in fact, Realm Studio can open the previous versions of the Realm but can only save them in the latest format of Realm. That is the reason why you want to wait.

I agree that this would give the ideal user experience: Being able to use a single version of Realm Studio to open (and write) any Realm file regardless of and without upgrading its underlying file format.

Since Realm Core and its file format is optimized primarily for the use-case of managing data from within a mobile device (besides being fast, it needs to be as small as possible in storage and memory), there's no real advantage (other than this feature in Realm Studio) in having the possibility of writing to a database file in an old file format. Therefore the first step for Realm Core when encountering an old file is to upgrade it to a format that it understands. It is therefore not possible from Realm JS (or Realm Studio) to read (or write) a file without upgrading it first.

We're tracking that feature with #1303 - this is an option we're also investigating, but we're hesitant since:
1. it would most likely pin our version of Electron too low (we would need to use a version which had a Realm JS binary compiled for the lowest file format that we want to support) and
2. it would complicate Realm Studio since we would potentially need multiple implementations to support the different versions of Realm JS
3. it would most likely increase the download size of Realm Studio by ~20mb.

> But only waiting will never really fix this issue. Realm Studio should not change the original format of the target Realm file at the first place.

This is an option too, but with the current architecture of Realm Core and the Realm DB files, Studio wouldn't be able to open DB files with an older format.

**Comment by owenzhao** [comment] 2020-09-19 12:02
OK. Now I fully understand why Realm Studio changed the file format even just read it. Oddly, but okay.

**Comment by deibidsonmesquita** [comment] 2020-09-20 22:55
Ansioso para solução deste problema

**Comment by joaodematejr** [comment] 2020-09-21 00:01
> Ansioso para solução deste problema

Você pode fazer um clone do projeto e rodar localmente to fazendo isso em quanto eles não lançam a versão final.

**Comment by liambolling** [comment] 2020-09-21 16:00
Any update on this?

**Comment by kejour** [comment] 2020-09-22 03:10
try [10.0.0-beta.2
](https://github.com/realm/realm-studio/releases/tag/v10.0.0-beta.2)

**Comment by bb-git** [comment] 2020-09-22 05:26
I followed the discussion here and I need to speak up. I personally feel, that this strategy is strongly patronizing as it basically tells: Realm users are unconsious and unresponsible and therefore we decided for them to protect them from making own decisions. But actually I think, that most of your users are very well aware of how software releases work. I read all the release notes before updating. I have the realm files I ship in the repository so I can always go back to an earlier version. So if there are users, that break their workflow with updating too early to a new version of Realm Studio, that's probably in their own responsibility. I suggest to look at it this way: Good software development skills go a long way. And you just help them on their way :).

Of course this is only MY opinion and it is YOUR product, so the decision is up to you. I just needed to communicate the emotions, that your explanation triggered inside me, as well as my anger, that I'm already shipping for iOS 14 with Xcode 12 and not being able use the newwest version and to port the realm files. So my wish for the future is to give back the responsibilty to your users. As well: Please consider not feeling responsible for the choices that your users make.
Thanks

**Comment by kraenhansen** [comment] 2020-09-22 06:46
@bb-git thanks for sharing that! That'll definitely stick with me. My understanding is that we have a large and diverse pool of users with vastly different backgrounds and experiences. In this case we just have prior experience releasing v3.11.0 which broke a lot of users flows - even if they had Git and could reset their files, they were still disturbed in their flow (had to reset files and manually downgrade to v3.10.0), which is why we decided to be extra conscious this time around - perhaps a bit too much :) Thanks again - definitely valuable input.

**Comment by kraenhansen** [comment] 2020-09-22 10:14
I'm very happy to announce that Realm Studio v5.0.0 has now been released.
The most important change is the ability to open Realm db files, using the v11 file format.

Links to download:
- [Realm Studio v5.0.0 for MacOS](http://studio-releases.realm.io/v5.0.0/download/mac-dmg)
- [Realm Studio v5.0.0 for Windows](http://studio-releases.realm.io/v5.0.0/download/win-setup)
- [Realm Studio v5.0.0 for Linux](http://studio-releases.realm.io/v5.0.0/download/linux-appimage)

**Closed by kraenhansen** 2020-09-22 10:14 UTC
Labels: O-Community
