### ISSUE TITLE
As a developer I can use Studio to see the size of each realm on the server

### ISSUE THREAD

**Issue by roberhofer** [realm/realm-studio#862] opened 2018-06-26 14:53 UTC
See as well tickets: 

\* [1080](https://github.com/realm/realm-object-server-private/issues/1080)

\*  [812](https://github.com/realm/realm-studio/issues/812)

Created from Aha! https://realmio.aha.io/features/ROS-31

**Comment by roberhofer** [comment] 2018-06-26 15:38
...

**Comment by kraenhansen** [comment] 2018-07-12 12:32
Duplicate of https://github.com/realm/realm-studio-private/issues/2.

**Closed by kraenhansen** 2018-07-12 12:32 UTC
