### ISSUE TITLE
11.0.0-beta.1 (dont work) Win 10

### ISSUE THREAD

**Issue by Avatarchik** [realm/realm-studio#1430] opened 2021-05-22 06:59 UTC
Uncaught Error: \\?\C:\Users\avatarchik\AppData\Local\Temp\40204144-80c7-49f9-9b11-6cfff9578eaf.tmp.node is not a valid Win32 application.
\\?\C:\Users\avatarchik\AppData\Local\Temp\40204144-80c7-49f9-9b11-6cfff9578eaf.tmp.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at bindings (C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\bindings\bindings.js:112)
    at getRealmConstructor (C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\lib\index.js:37)
    at Object.<anonymous> (C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\lib\index.js:62)
    at Object.<anonymous> (C:\Program Files\MongoDB Realm Studio\resources\app.asar\node_modules\realm\lib\index.js:71)
    at Module._compile (internal/modules/cjs/loader.js:1152)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173)
    at Module.load (internal/modules/cjs/loader.js:992)
    at Module._load (internal/modules/cjs/loader.js:885)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Module.require (internal/modules/cjs/loader.js:1032)
    at require (internal/modules/cjs/helpers.js:72)
    at Object.<anonymous> (C:\Program Files\MongoDB Realm Studio\resources\app.asar\build\renderer.bundle.js:1)
    at r (C:\Program Files\MongoDB Realm Studio\resources\app.asar\build\renderer.bundle.js:1)
    at C:\Program Files\MongoDB Realm Studio\resources\app.asar\build\renderer.bundle.js:1
    at processTicksAndRejections (internal/process/task_queues.js:79)

**Comment by kraenhansen** [comment] 2021-05-26 14:28
@Avatarchik it looks like you're using the 32bit version of Windows 10. Is that correct?

In that case, this would be the first time I've seen interest from a user to run Studio on a 32 bit system. With [Microsoft winding down its interest in distributing a 32 bit variant of Windows](https://www.engadget.com/windows-10-32-bit-oem-173055990.html) I see limited incentive to build and distribute Realm Studio for 32 bit Windows.

Please reopen this issue if you're not on a 32 bit system.

**Comment by Avatarchik** [comment] 2021-05-26 17:10
Hi! I am using x64

**Comment by kraenhansen** [comment] 2021-05-26 18:35
@Avatarchik that's interesting indeed. I'll reopen and try to reproduce. Do you know if there's anything that might be special about your system?

**Comment by Avatarchik** [comment] 2021-05-26 18:52
Windows 10 Home Edition
Version 20H2
Installation date 16.06.2020
OS Build 19042.985
Interoperability Windows Feature Experience Pack 120.2212.2020.0

**Comment by bimusiek** [comment] 2021-06-10 16:12
@kraenhansen We have the same issue in our Electron build after upgrading to Realm 10.4.2. (Using Electron 12.0.1)
<img width="587" alt="CleanShot 2021-06-10 at 18 02 45@2x" src="https://user-images.githubusercontent.com/1025588/121559481-e1201700-ca16-11eb-951f-f82eec2c40a1.png">

**Comment by kraenhansen** [comment] 2021-07-05 06:21
This should be fixed in the latest release (v11.0.1)

**Closed by kraenhansen** 2021-07-05 06:21 UTC
Labels: O-Community
