### ISSUE TITLE
Connect buttons are missing

### ISSUE THREAD

**Issue by jakehockey10** [realm/realm-studio#1363] opened 2020-11-21 18:09 UTC
**Describe the bug**
The docs pages describe how there is a button to click that will allow you to connect to a cloud instance.  So I go to team's cloud instance url, it has a download button for realm studio.  I download it, install it, and open it.  There is only a button to open a local realm file.  There is no connect to server or connect to cloud buttons like the docs say.

**To Reproduce**
1. See above.

**Expected behavior**
I would expect that realm studio let's me connect to my cloud instance like the screenshots and text indicate in the docs.

**Screenshots**
What I see:
![image](https://user-images.githubusercontent.com/1821383/99884223-cb1d4700-2be9-11eb-8d27-836c17a86fa8.png)

What the docs say I should see:
![image](https://user-images.githubusercontent.com/1821383/99884234-d96b6300-2be9-11eb-8412-9d45395311b6.png)

**Versions:**
 - OS: Windows
 - Studio Version 10.0.1
 - Realm Object Server version (Not sure how to tell.)

**Additional context**
I'm not the original maintainer of the project using this database, but I do rely on being able to query it.  I'm seeing some odd behavior between a mobile app and a web app that we've written (different data, supposedly same database), and I'd like to investigate this.

**Comment by kraenhansen** [comment] 2020-11-21 18:49
First of, thanks for reporting an issue!

What docs pages specifically are you referring to?

You're mentioning a version of Realm Studio which is ment to work with the MongoDB Realm application development platform, which does not currently support connecting to a server. If you ment to download a version which can connect to the legacy Realm Cloud, please use a download link on this release: https://github.com/realm/realm-studio/releases/tag/v5.0.1

I'm closing this issue since I believe it works as intended.

**Comment by jakehockey10** [comment] 2020-11-22 00:31
The docs I meant are the ones on realm.io.  They are the ones in my second screenshot.  We must be using the MongoDB one like you say.

**Closed** 2020-11-22 07:28 UTC
Labels: O-Community
