### ISSUE TITLE
Realm Studio 11.0 will not open my v22 realm file

### ISSUE THREAD

**Issue by tfrysinger** [realm/realm-studio#1439] opened 2021-06-27 16:30 UTC
Trying to open a v22 realm file does not work - I just get an empty screen (no errors, no nothing).

**To Reproduce**
Attempt to open the attached .realm file

**Expected behavior**
The file should open per normal Realm Studio semantics

**Screenshots**

**Versions:**
 - Windows 10
 - Mongo DB Realm Studio Version 11.0
 - Realm Object Server version N/A
[intouchrealm.zip](https://github.com/realm/realm-studio/files/6721921/intouchrealm.zip)

**Additional context**

**Comment by emadridm** [comment] 2021-06-27 22:16
MongoDB Realm Studio does not render info.

**Release:** 
MongoDB Realm Studio-11.0.0.AppImage

**OS**
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

**Comment by Chaser324** [comment] 2021-06-27 23:55
Same here. I open the file and then just get a blank screen. Older versions of Realm Studio work (throw expected error on v22 file, but works on other realm files).

- Windows 10 Home (Build 19041)
- Realm Studio v11.0.0 (both portable and installed)

**Comment by expiteRz** [comment] 2021-06-28 09:21
Same. I only can see white screen in opening my Realm database file.

- Windows 10 Home Build 19043
- Realm Studio v11.0.0

**Comment by ThisIsABug** [comment] 2021-06-29 12:01
Same here.
- Windows 10 Version 20H2
- Realm Studio  v11.0.0

**Comment by takameyer** [comment] 2021-06-29 14:39
We were able to reproduce the issue on Windows and will look into it as soon as we can.

**Comment by kraenhansen** [comment] 2021-06-29 22:36
Thanks for bringing this to our attention. Needless to say, unfortunately this wasn't caught by the projects automatic tests, which we need to revisit and build out.

We've reproduced and I've identified to root cause: The `prebuild-install` of our Realm JS installs a darwin binary into the `node_modules/realm/build/Release/realm.node` and `electron-builder` doesn't rebuild the native dependency when building for Windows the same way it did before our switch to `prebuild`. Next step is to investigate if `electron-builder` can be configured to play well with the `prebuild` package.

**Comment by tfrysinger** [comment] 2021-06-29 22:56
Thanks for the update. Probably stating the obvious but I'd strongly suggest augmenting your tests to have them attempt opening every realm file version that a particular build is supposed to support (and negative tests to insure it won't open versions it isn't supposed to).

**Comment by bmunkholm** [comment] 2021-06-30 09:37
Thanks for your patience, this is now fixed in 11.0.1: https://github.com/realm/realm-studio/releases/tag/v11.0.1. Studio should automatically ask you to upgrade.

**Closed by bmunkholm** 2021-06-30 09:37 UTC
Labels: O-Community

**Comment by tfrysinger** [comment] 2021-06-30 14:11
Confirmed that this now opens my v22 file that was failing before.
