### ISSUE TITLE
realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture

### ISSUE THREAD

**Issue by MuratAkbaba006** [realm/realm-studio#1504] opened 2022-05-30 21:39 UTC
**Describe the bug**
I try to open realm file in realm studio when ios emulator is running.  I am getting an error like this 'realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture.'

**To Reproduce**
1. Run the react native app with ios emulator
2. try to open realm file with Realm Studio
3. See error

**Expected behavior**
I want to see realm file contents when my app is running

**Screenshots**
<img width="1429" alt="Screen Shot 2022-05-31 at 00 26 32" src="https://user-images.githubusercontent.com/44754934/171061216-b82cb21e-482c-4fbe-ba53-c8820dde7875.png">

**Versions:**
 - OS: MacbookPro 2020 Version 12.3.1 i5 processor
 - Realm Studio 11.1.2

<img width="1429" alt="Screen Shot 2022-05-31 at 00 26 32" src="https://user-images.githubusercontent.com/44754934/171061519-c362cc2e-1b23-41b4-a84d-8509ea887b47.png">

**Comment by MuratAkbaba006** [comment] 2022-06-01 07:26
In M1 processor it seems to work fine but in intel, it gives this error. We work on this project with both M1 and intel macs. Is there a configuration file that we can reset on our local development environment for the realm or xcode?

**Comment by faruk-arslan** [comment] 2022-06-01 07:27
> **Describe the bug** I try to open realm file in realm studio when ios emulator is running. I am getting an error like this 'realm file is currently open in another process which cannot share access with this process. All processes sharing a single file must be the same architecture.'
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run the react native app with ios emulator
> 2. try to open realm file with Realm Studio
> 3. See error
> 
> **Expected behavior** I want to see realm file contents when my app is running
> 
> **Screenshots** <img alt="Screen Shot 2022-05-31 at 00 26 32" width="1429" src="https://user-images.githubusercontent.com/44754934/171061216-b82cb21e-482c-4fbe-ba53-c8820dde7875.png">
> 
> **Versions:**
> 
> * OS: MacbookPro 2020 Version 12.3.1 i5 processor
> * Realm Studio 11.1.2
> 
> <img alt="Screen Shot 2022-05-31 at 00 26 32" width="1429" src="https://user-images.githubusercontent.com/44754934/171061519-c362cc2e-1b23-41b4-a84d-8509ea887b47.png">

I also started to see the same problem

**Comment by kraenhansen** [comment] 2022-06-01 11:15
Thanks for reporting your issue, I'm closing this as a duplicate of #1503

**Comment by kraenhansen** [comment] 2022-06-01 12:51
I'm reopening this as per [this comment](https://github.com/realm/realm-studio/issues/1503#issuecomment-1143563902): It appears to occur when the app is running Realm JS v10.10.0 (in the iOS simulator), which doesn't use v12.0.0 of Realm Core, as I initially suspected.

**Comment by kraenhansen** [comment] 2022-06-07 19:07
@MuratAkbaba006 can I have you download [Realm Studio v12.0.0](https://github.com/realm/realm-studio/releases/tag/v12.0.0), to verify that this issue is still happening for you?

**Comment by MuratAkbaba006** [comment] 2022-06-07 19:17
now, everything looks good. thank you @kraenhansen

**Closed as not planned** 2022-06-07 19:39 UTC
Labels: O-Community
