### ISSUE TITLE
When upgrading Studio it doesn't restart

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#526] opened 2017-12-12 13:38 UTC
![image](https://user-images.githubusercontent.com/1215687/33725353-bf096a8c-db26-11e7-9a77-2a9b39fcbeee.png)

No way to use the new version?

When I restart Studio, it downloads version 10 again. And this time with the popup appearing (on another screen than Studio is. Hidden behind a browser window. Was only visible because the Icon in the Dock was flashing.

**Comment by kraenhansen** [comment] 2019-03-07 09:51
I consider this a duplicate of https://github.com/realm/realm-studio/issues/1129

**Closed by kraenhansen** 2019-03-07 09:51 UTC
Labels: P:2 Expected, T:Duplicate
