### ISSUE TITLE
Realm Studio often starts doing some heavy processing in the background

### ISSUE THREAD

**Issue by geragray** [realm/realm-studio#1142] opened 2019-04-16 15:24 UTC
Realm Studio often starts doing some heavy processing in the background, taking almost 100% of processing power.

_Originally posted by @ianpward in https://github.com/realm/realm-java-private/issues/258#issuecomment-483428910_

**Comment by nirinchev** [comment] 2019-04-16 15:58
This is a duplicate of https://github.com/realm/realm-studio/issues/1125

**Closed by nirinchev** 2019-04-16 15:58 UTC
