### ISSUE TITLE
Fine-grained permissions: See a users privileges

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#1002] opened 2018-11-15 09:40 UTC
**Use case:**
When working with fine-grained permissions it would be very helpful to be able to see exactly what privileges a different user has. Having this means developers can use Studio to ensure that they implemented their intended permission model correctly 

**Implementation:**
UX for this needs to be designed first.

The easiest would probably be just allowing admins to open a Realm as read-only as a given user (although it might also be a bit confusing if there is no indication it is the user's Realm). 

Any other solution will require a harder look at Sync/Binding API's as there is currently no way to learn a user's privileges without actually logging in as one

**Comment by kraenhansen** [comment] 2018-11-19 14:30
When an admin opens a reference now, they can see and change all objects. Perhaps we could add a mode to "See as another user" where the browser would gray-out and disable inputs for all objects which the user does not has read and write access to respectively.

Alternatively I would say that admins should open the partial Realm created by a user to see what objects that particular user has access to - would that work @cmelchior?

**Comment by kraenhansen** [comment] 2018-12-03 15:42
@cmelchior would ☝️ work for your use-case?

**Comment by kraenhansen** [comment] 2019-01-07 15:58
Because admins can already open the device specific partial Realm to see what users has access to (given that the user has created subscriptions for these), perhaps we can close this issue? If that is not what you were looking for @cmelchior, can you talk a bit more about what solution / UX you think would be ideal here? Perhaps @roberhofer or @bmunkholm can add some thoughts since it's in the top of the next sprint backlog?

**Comment by roberhofer** [comment] 2019-01-08 23:33
@cmelchior , @kraenhansen : Agree. Think that this is a duplicate of https://github.com/realm/realm-studio-private/issues/12. Resolving as such. Christian: please review the other issue.

**Closed by roberhofer** 2019-01-08 23:33 UTC
Labels: Design Required, T:Duplicate, T:Feature
