### ISSUE TITLE
Opening Realm files of format version 11 is not supported by this version of Realm

### ISSUE THREAD

**Issue by lutluthfi** [realm/realm-studio#1330] opened 2020-09-17 05:44 UTC
**Describe the bug**
I can't open the Realm file which has been generated automatically by iOS application from simulator.

**To Reproduce**
1. Go to `~/Library/Developer/CoreSimulator/Devices/{Device's UUID}/data/Containers/Data/Application/{Application's UUID}/Documents/default.realm`
2. Double click on `default.realm` file

**Expected behavior**
I can open and take some actions like view and edit to the Realm file

**Screenshots**
<img width="686" alt="Screen Shot 2020-09-17 at 12 43 34" src="https://user-images.githubusercontent.com/16360926/93425027-6987e600-f8e3-11ea-9ec9-38ccca6f1076.png">

**Versions:**
 - OS: MacOS 10.15.6 
 - Studio Version: 3.11.0 (3.11.0.719)
 - Realm (Cocoapods): 5.4.0

**Comment by flyinghawker** [comment] 2020-09-17 13:39
get me stuck too, plz help

**Comment by flyinghawker** [comment] 2020-09-17 14:01
I roll RealmSwift back to 4.4.1 and it works fine. So there must be issue with that. 
Ok, I can start work with older version anyway. ^_^

**Comment by aregler** [comment] 2020-09-17 14:19
yep should be the same issue as in #1325

**Comment by lutluthfi** [comment] 2020-09-17 15:30
> I roll RealmSwift back to 4.4.1 and it works fine. So there must be issue with that. 
> 
> Ok, I can start work with older version anyway. ^_^

Any suggestions for a later version than 4.4.1?

**Comment by kolakovskijj** [comment] 2020-09-17 18:44
Same issue here 

Opening Realm files of format version 11 is not supported by this version of Realm

<img width="1113" alt="Screen Shot 2020-09-17 at 1 42 25 PM" src="https://user-images.githubusercontent.com/45243948/93513708-e028e180-f8eb-11ea-80c1-bc1925b7ae1e.png">

**Comment by flyinghawker** [comment] 2020-09-18 01:45
> > I roll RealmSwift back to 4.4.1 and it works fine. So there must be issue with that.
> > Ok, I can start work with older version anyway. ^_^
> 
> Any suggestions for a later version than 4.4.1?

not yet, because the issue just happened to me when I upgrade version from 4.4.1(my project was with version 4.4.1).

**Comment by joaodematejr** [comment] 2020-09-18 13:00
+1

**Comment by kraenhansen** [comment] 2020-09-18 20:59
Closing this as a duplicate of https://github.com/realm/realm-studio/issues/1325

**Closed by kraenhansen** 2020-09-18 20:59 UTC
Labels: O-Community
