### ISSUE TITLE
ARM64 Support on macOS

### ISSUE THREAD

**Issue by bdkjones** [realm/realm-studio#1531] opened 2022-09-06 09:17 UTC
We're on the second generation of Apple Silicon chips already. They've been out for years at this point. Realm-Studio is already painfully slow and clunky on macOS, so running through Rosetta instead of natively isn't doing the app any favors.

Please provide a native `arm64` version of the app via a Universal Binary.

**Comment by kneth** [comment] 2022-09-06 13:14
@bdkjones I fully understand the usefulness for support of Apple silicon. To be honest, we haven't prioritized it recently but since the entire team is in the same situation, it might be time to look into it.

I am closing the issue as it is a duplicate of https://github.com/realm/realm-studio/issues/1469

**Closed as completed by kneth** 2022-09-06 13:14 UTC
Labels: O-Community
