### ISSUE TITLE
The file is already opened by another process, with an incompatible lock file format. Try up- or downgrading Realm Studio or SDK to match their versions of Realm Core.

### ISSUE THREAD

**Issue by PGM21-json** [realm/realm-studio#1518] opened 2022-06-14 10:01 UTC
**Describe the bug**
Receiving the 'Failed to Open Realm' error message when trying to open a Realm file on Mac
"The file is already opened by another process, with an incompatible lock file format. Try up- or downgrading Realm Studio or SDK to match their versions of Realm Core."

I'm running RealmSwift 10.28 and Realm Studio 12.0.0, which change log suggests should be compatible.

A different message did come up once regarding making backup compatible, which enabled me to open the file, but haven't seen that pop-up since.

**To Reproduce**
Attempt to open realm file in Realm Studio

**Expected behavior**
View realm database

**Screenshots**

**Versions:**
 - OS: Macbook Pro
 - Studio Version: 12.0.0

**Comment by tomduncalf** [comment] 2022-06-15 09:24
Hey @PGM21-json, thanks for the report. We are investigating this and will get back to you when we have an update.

**Comment by tomduncalf** [comment] 2022-06-15 16:14
Hi @PGM21-json, I tried taking the [Realm Swift Task Tracker example](https://github.com/realm/task-tracker-swiftui) and upgraded to Realm Swift 10.28.1, and I was still able to open the Realm file in Realm Studio 12.0.0.

Could you share a bit more information about your setup/project? I was running my test in the iOS simulator. If you're able to create a simple reproduction for your issue (e.g. with the task tracker app or a simple test app which you can share), that would be really helpful.

**Comment by timahrentlov** [comment] 2022-06-17 13:17
I see the same thing using Xamarin. I've always been able to run the app in the simulator and access the realm using the  MongoDB Realm Studio. It's paramount in order to test reactivity. This is currently not possible.

I'm using the newest of everything.

**Comment by tomduncalf** [comment] 2022-06-17 13:19
@timahrentlov Are you able to share a reproduction please? A simple project that I can run to create a Realm file that can't be opened, for example. As I mentioned above, I tried using realm-swift on the latest version and was not able to reproduce this issue

**Comment by timahrentlov** [comment] 2022-06-17 13:47
@tomduncalf I'm afraid not. Not right now at least.

**Comment by kraenhansen** [comment] 2022-06-17 15:30
> I'm using the newest of everything.

@timahrentlov Please share the exact versions of the SDK and Studio you're using 🙏

**Comment by timahrentlov** [comment] 2022-06-20 06:47
> > I'm using the newest of everything.
> 
> @timahrentlov Please share the exact versions of the SDK and Studio you're using 🙏

Hi Kræn,

I'm using realm version 10.14.0 and MongoDB Realm Studio 11.2.1

**Comment by kraenhansen** [comment] 2022-06-20 07:29
Studio doesn't prompt users to upgrade across major versions (yet). Please download Realm Studio v12 and try again: https://github.com/realm/realm-studio/releases/tag/v12.0.0

**Comment by timahrentlov** [comment] 2022-06-20 07:49
That worked!
Tak Kræn

**Comment by tomduncalf** [comment] 2022-06-20 12:47
Hi @PGM21-json, did you have any updates on this from your side or a reproduction case? Thanks

**Comment by PGM21-json** [comment] 2022-06-20 20:46
@tomduncalf, not able to at the moment - Would it help if I shared a Realm file to see if you can open in Studio?

**Comment by tomduncalf** [comment] 2022-06-21 08:44
@PGM21-json Yeah that would be good, thanks.

**Comment by PGM21-json** [comment] 2022-06-21 09:42
@tomduncalf - I've emailed over.

**Comment by tomduncalf** [comment] 2022-06-21 09:51
Thanks @PGM21-json, I was able to open the file in Realm Studio 12. It did show this warning on opening: 
![image](https://user-images.githubusercontent.com/5458070/174771483-36751a71-11b3-4c70-915e-eb90d21f3352.png)

Can you check that you are opening Realm Studio 12 and not 11? The name of the app changed, so it's possible that you are opening v11 ("MongoDB Realm Studio") and not v12 ("Realm Studio")

![image](https://user-images.githubusercontent.com/5458070/174771599-388020c4-08d3-44f5-a120-4cab2f7a0353.png)

**Comment by PGM21-json** [comment] 2022-06-21 15:12
Definitely showing as v12.
<img width="812" alt="Screenshot 2022-06-21 at 16 09 27" src="https://user-images.githubusercontent.com/75266539/174834418-6c513379-611d-493a-9206-c706d84b51d1.png">

That's the pop up I'd had once before which let me access the file, but I've never seen that option since. I just get this every time now...(attempting to open same Realm as I sent to you)
<img width="1132" alt="Screenshot 2022-06-21 at 16 11 36" src="https://user-images.githubusercontent.com/75266539/174834770-6536b5c8-9363-4e10-80ca-b5540b36c46e.png">

**Comment by tomduncalf** [comment] 2022-06-22 08:44
Hey @PGM21-json, that's really strange – this is opening the exact same file that you sent to me? Is the Simulator running at the time you try to access it? If so, could you try closing it before opening the Realm? Also, could you try restarting your machine?

**Comment by kneth** [comment] 2022-07-08 15:48
@PGM21-json Any updates to share?

**Comment by tomduncalf** [comment] 2022-07-27 10:31
@PGM21-json I am going to close this ticket as we have not heard back from you. If you are still having issues please feel free to re-open it with more details.

**Closed as completed by tomduncalf** 2022-07-27 10:31 UTC
Labels: O-Community, More-information-needed
