### ISSUE TITLE
Unable to open a realm at path '/Users/../default.realm'  Invalid top array (ref: 1164152, size: 11)

### ISSUE THREAD

**Issue by ro6lyo** [realm/realm-studio#1308] opened 2020-06-13 16:06 UTC
**Describe the bug**
When open default.realm exported from iOS project. Realm Studio show error, Realm Browsers opens encryption dialog, but the DB is not encrypted at all !
It happened after migration of  RealmSwift from 3.14.1 to 5.0.3 (without migration of the SDK it work as expected)

**To Reproduce**

1. Use realm in iOS  project
2. Import Realm DB in project directory
3. Copy imported Realm to Device home directory and use it.

/Users/<username>/Library/Developer/CoreSimulator/Devices/<simulator-uuid>/data/Containers/Data/Application/<application-uuid>/Documents/
4. Open default.realm
5. Realm Studio show error
6. Realm browser shows encryption key dialog

**Expected behavior**
Open and interaction with default.realm file

**Screenshots**
[https://github.com/ro6lyo/assets/blob/master/Screenshot%202020-06-13%20at%2019.04.00.png](url)

**Versions:**
 - OS: macOS Catalina 10.15.5
 - Studio Version 3.10.0
 - Realm Browser version 3.0.1

**Comment by hugofovargue** [comment] 2020-06-22 16:49
Second this. 

#### Versions:

OS: macOS Catalina `10.14.6`
React Native version `0.62.2`
Realm Studio version `3.10.0`
Realm-js version `6.0.1`

For me this was after migrating from realm-js `3.6.0` to `6.0.1`, and RN from `0.61.5` to `0.62.2`.
So far I've been unable to open any realm files created with `6.0.1` but have been able to open the demo file.

I'll downgrade to `3.6.0` for now.

#### Stack trace

```
CLASSES
Unable to open a realm at path '/Users/hugofovargue/Library/Developer/CoreSimulator/Devices/A5EC7380-3354-402B-98B6-C30C9CB64082/data/Containers/Data/Application/3F6E546A-EEB9-4098-88B8-3A7F90A15FED/Documents/default.realm': Invalid top array (ref: 18192, size: 11)
Exception backtrace:
0 .io.realm.realm-studio.gHQz8q 0x0000000117715271 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 49
1 .io.realm.realm-studio.gHQz8q 0x0000000117703660 _ZN5realm5Group18validate_top_arrayERKNS_5ArrayERKNS_9SlabAllocE + 1632
2 .io.realm.realm-studio.gHQz8q 0x000000011770d710 _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 5136
3 .io.realm.realm-studio.gHQz8q 0x0000000117410a1c _ZN5realm11SharedGroup4openERNS_11ReplicationENS_18SharedGroupOptionsE + 236
4 .io.realm.realm-studio.gHQz8q 0x0000000117410403 _ZN5realm11SharedGroupC2ERNS_11ReplicationENS_18SharedGroupOptionsE + 1587
5 .io.realm.realm-studio.gHQz8q 0x000000011737aff1 _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEEPS0_ + 1145
6 .io.realm.realm-studio.gHQz8q 0x000000011737a926 _ZN5realm5RealmC2ENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 278
7 .io.realm.realm-studio.gHQz8q 0x000000011738127e _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC2ES1_S6_ + 84
8 .io.realm.realm-studio.gHQz8q 0x000000011739ada8 _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigENS0_INS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerE11make_sharedIJS3_S6_EEES8_DpOT_ + 136
9 .io.realm.realm-studio.gHQz8q 0x0000000117395f7c _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EERNS4_11unique_lockINS4_5mutexEEEb + 260
10 .io.realm.realm-studio.gHQz8q 0x0000000117395dea _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 352
11 .io.realm.realm-studio.gHQz8q 0x000000011737cc9b _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 113
12 .io.realm.realm-studio.gHQz8q 0x00000001172e1cab _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEPN2v87IsolateENS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedINS5_5LocalINS5_5ValueEEEEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_INSJ_INS5_8FunctionEEEEESO_NSF_INSP_ISQ_S10_EEEEEE + 127
13 .io.realm.realm-studio.gHQz8q 0x00000001172e00a6 _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEPN2v87IsolateENS5_5LocalINS5_6ObjectEEERNS0_9ArgumentsIS3_EE + 402
14 .io.realm.realm-studio.gHQz8q 0x00000001172df3fb _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE + 333
15 .io.realm.realm-studio.gHQz8q 0x00000001172dfdf2 _ZN3Nan3impL23FunctionCallbackWrapperERKN2v820FunctionCallbackInfoINS1_5ValueEEE + 166
16 Electron Framework 0x000000010cf344a8 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 350504
17 Electron Framework 0x000000010cefdada _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 126810
18 Electron Framework 0x000000010cefd3a7 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 124967
19 Electron Framework 0x000000010d844dce _ZN2v88internal6Parser31BuildIteratorCloseForCompletionEPNS0_8ZoneListIPNS0_9StatementEEEPNS0_8VariableEPNS0_10ExpressionENS0_12IteratorTypeE + 1450046 Path:Exception backtrace:
0 .io.realm.realm-studio.gHQz8q 0x0000000117715271 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 49
1 .io.realm.realm-studio.gHQz8q 0x000000011770f253 _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 12115
2 .io.realm.realm-studio.gHQz8q 0x0000000117410a1c _ZN5realm11SharedGroup4openERNS_11ReplicationENS_18SharedGroupOptionsE + 236
3 .io.realm.realm-studio.gHQz8q 0x0000000117410403 _ZN5realm11SharedGroupC2ERNS_11ReplicationENS_18SharedGroupOptionsE + 1587
4 .io.realm.realm-studio.gHQz8q 0x000000011737aff1 _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEEPS0_ + 1145
5 .io.realm.realm-studio.gHQz8q 0x000000011737a926 _ZN5realm5RealmC2ENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 278
6 .io.realm.realm-studio.gHQz8q 0x000000011738127e _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC2ES1_S6_ + 84
7 .io.realm.realm-studio.gHQz8q 0x000000011739ada8 _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigENS0_INS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerE11make_sharedIJS3_S6_EEES8_DpOT_ + 136
8 .io.realm.realm-studio.gHQz8q 0x0000000117395f7c _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EERNS4_11unique_lockINS4_5mutexEEEb + 260
9 .io.realm.realm-studio.gHQz8q 0x0000000117395dea _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 352
10 .io.realm.realm-studio.gHQz8q 0x000000011737cc9b _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 113
11 .io.realm.realm-studio.gHQz8q 0x00000001172e1cab _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEPN2v87IsolateENS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedINS5_5LocalINS5_5ValueEEEEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_INSJ_INS5_8FunctionEEEEESO_NSF_INSP_ISQ_S10_EEEEEE + 127
12 .io.realm.realm-studio.gHQz8q 0x00000001172e00a6 _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEPN2v87IsolateENS5_5LocalINS5_6ObjectEEERNS0_9ArgumentsIS3_EE + 402
13 .io.realm.realm-studio.gHQz8q 0x00000001172df3fb _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE + 333
14 .io.realm.realm-studio.gHQz8q 0x00000001172dfdf2 _ZN3Nan3impL23FunctionCallbackWrapperERKN2v820FunctionCallbackInfoINS1_5ValueEEE + 166
15 Electron Framework 0x000000010cf344a8 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 350504
16 Electron Framework 0x000000010cefdada _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 126810
17 Electron Framework 0x000000010cefd3a7 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 124967
18 Electron Framework 0x000000010d844dce _ZN2v88internal6Parser31BuildIteratorCloseForCompletionEPNS0_8ZoneListIPNS0_9StatementEEEPNS0_8VariableEPNS0_10ExpressionENS0_12IteratorTypeE + 1450046.
```

**Comment by kraenhansen** [comment] 2020-06-25 14:37
[Please download Realm Studio v3.11.0](https://github.com/realm/realm-studio/releases/tag/v3.11.0). It uses a newer version of the Realm file format, which is needed to open files from the newer SDK versions.

This is most likely a duplicate of https://github.com/realm/realm-studio/issues/1288, https://github.com/realm/realm-studio/issues/1281 and https://github.com/realm/realm-studio/issues/1241. Please reopen if the issue persists after upgrading.

**Closed** 2020-06-25 14:42 UTC
Labels: O-Community
