### ISSUE TITLE
[Mac] Cannot delete multiple objects at once

### ISSUE THREAD

**Issue by amalmo** [realm/realm-studio#959] opened 2018-10-04 08:55 UTC
**Describe the bug**
Unable to delete all selected objects in Realm Studio for Mac.

**To Reproduce**
1. Go a class
2. Select two or more objects
3. Right click and select "Delete selected object"

Only the actual object you right clicked on is deleted.

This was working fine in 2.8.0 if I remember correctly

**Expected behavior**
Delete all selected objects.

**Versions:**
 - OS: Mac
 - Studio Version 2.9.0
 - Realm Object Server version 3.11.0

**Comment by kraenhansen** [comment] 2018-11-12 10:44
This got fixed by https://github.com/realm/realm-studio/pull/961 and released in version 3.0.0 of Studio.

**Closed by kraenhansen** 2018-11-12 10:44 UTC
Labels: O:User, T:Bug

**Comment by homathko** [comment] 2019-03-28 15:02
Hello, having the exact same issue with Realm Studio 3.5.0, macOS 10.14.2

**Comment by kraenhansen** [comment] 2019-04-10 06:26
@homathko I just tried in Realm Studio 3.5.0 on MacOS 10.14.4 and I cannot reproduce the issue. Could I get you to record a small video / gif with this and upload it somewhere?
