### ISSUE TITLE
Confusing popup when connection from cloud.realm.io

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#899] opened 2018-08-16 06:22 UTC
When opening Realm Studio from `cloud.realm.io` you get the following popup:

![image](https://user-images.githubusercontent.com/406066/44191790-fec8b700-a12c-11e8-85bd-ca50dfa7fffd.png)

IMO it is very confusing. Even I have very little idea what it means (I assume it means that Github somehow sees the Cloud token). 

If it is insecure to open Studio from the browser why are we doing it in the first place?
If it is secure, why show a confusing popup?
Why do we need to connect to Github? I already logged in using Github credentials?

As minimum we should change the wording so it is more explicit about what "server" means.

**Comment by kraenhansen** [comment] 2018-08-16 13:03
Duplicate of https://github.com/realm/raas/issues/387

**Closed by kraenhansen** 2018-08-16 13:03 UTC
