### ISSUE TITLE
Can't upgrade from 2.5.0 to 2.8.0

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#936] opened 2018-09-05 11:00 UTC
Probably similar to https://github.com/realm/realm-studio/issues/929

<img width="606" alt="screen shot 2018-09-05 at 11 59 01" src="https://user-images.githubusercontent.com/1793238/45089185-4a0a3000-b103-11e8-9495-1da6605a62ba.png">

When I click ok I have this message twice

![image](https://user-images.githubusercontent.com/1793238/45089253-7b82fb80-b103-11e8-88a8-d7e9cf465b26.png)

**Comment by nirinchev** [comment] 2018-10-31 10:11
Duplicate of https://github.com/realm/realm-studio/issues/929

**Closed by nirinchev** 2018-10-31 10:11 UTC
Labels: T:Bug
