### ISSUE TITLE
Can not open file: Opening Realm files of format version 11 is not supported by this version of Realm

### ISSUE THREAD

**Issue by Mazorati** [realm/realm-studio#1335] opened 2020-09-21 13:23 UTC
**Describe the bug**
Opening Realm files of format version 11 is not supported by this version of Realm

**To Reproduce**

```
import RealmSwift
extension Realm.Configuration {
    static let shared: Realm.Configuration = {
        let fileURL = try! FileManager.default
            .url(for: .libraryDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
            .appendingPathComponent("default.realm")

        Logger.debug(fileURL)
        return Realm.Configuration(fileURL: fileURL)
    }()
}
```
1. Run:
`let realm = try! Realm(configuration: Realm.Configuration.shared)`
2. Copy path from console
3. in terminal:
`open /Users/.../data/Containers/Data/Application/E9262C93-68D4-477D-AF9F-CA4835541596/Library/default.realm`
4. See the error

**Expected behavior**
Realm Studion opens the database created

**Screenshots**
<img width="668" alt="Screenshot 2020-09-21 at 15 20 49" src="https://user-images.githubusercontent.com/3396425/93771701-28167400-fc1e-11ea-9e6a-aa2ff8730e78.png">

**Versions:**
 - OS: Mac 10.15.6
 - Studio Version 3.11.0

**Additional context**
- Realm (5.4.2):
- Realm/Headers (= 5.4.2)
- Realm/Headers (5.4.2)

**Comment by steffenagger** [comment] 2020-09-21 13:44
Duplicate of https://github.com/realm/realm-studio/issues/1325, please follow this instead for updates.

**Closed by steffenagger** 2020-09-21 13:44 UTC
Labels: O-Community
