### ISSUE TITLE
realm db file opens blank or returning "Invalid top array..."

### ISSUE THREAD

**Issue by jychj** [realm/realm-studio#1471] opened 2022-01-06 12:06 UTC
I'm generating .realm files from an iOS app that I then download and process on my computer. For some reasons, some of the .realm files can't open (seems random which ones) and one of two things happen: a blank db opens up (no data entries shown even though the file is not empty); an error message is shown (Unable to open a realm at path '...': Invalid top array (ref: 8012824, size: 3176960)
Exception backtrace:...". I have tried multiple versions of realm studio (3.10, 3.11, 10.0, 10+) using windows 10 PC.

I hope the data within the files can be recovered - attached two example files.

[example files.zip](https://github.com/realm/realm-studio/files/7821566/example.files.zip)

(I'm not a developer)

**Comment by kraenhansen** [comment] 2022-01-07 15:00
Based on the headers of the files, they should be opened with Realm Studio v3.

I was able to extract the following crash while opening the `opens_blank.realm`:

```
../src/realm/table.cpp:507: [realm-core-5.23.8] Assertion failed: m_top.size() == 2 [12, 2]
0   .io.realm.realm-studio.WPJrcC       0x0000000112cfe17c _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   .io.realm.realm-studio.WPJrcC       0x0000000112cfe436 _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 390
2   .io.realm.realm-studio.WPJrcC       0x00000001127fce21 _ZN5realm4util9terminateIJmiEEEvPKcS3_lDpT_ + 56
3   .io.realm.realm-studio.WPJrcC       0x0000000112ca7eb5 _ZN5realm5Table4initEmPNS_11ArrayParentEmb + 1141
4   .io.realm.realm-studio.WPJrcC       0x0000000112bae226 _ZN5realm5Group21create_table_accessorEm + 246
5   .io.realm.realm-studio.WPJrcC       0x0000000112bae09e _ZN5realm5Group12do_get_tableEmPFbRKNS_4SpecEE + 254
6   .io.realm.realm-studio.WPJrcC       0x000000011280e6f1 _ZN5realm11ObjectStore18get_schema_versionERKNS_5GroupE + 45
7   .io.realm.realm-studio.WPJrcC       0x0000000112826af8 _ZN5realm5Realm32read_schema_from_group_if_neededEv + 76
8   .io.realm.realm-studio.WPJrcC       0x00000001128259b3 _ZN5realm5Realm10read_groupEv + 43
9   .io.realm.realm-studio.WPJrcC       0x00000001128249eb _ZN5realm5RealmC2ENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 475
10  .io.realm.realm-studio.WPJrcC       0x000000011282b27e _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC2ES1_S6_ + 84
11  .io.realm.realm-studio.WPJrcC       0x0000000112844da8 _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigENS0_INS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerE11make_sharedIJS3_S6_EEES8_DpOT_ + 136
12  .io.realm.realm-studio.WPJrcC       0x000000011283ff7c _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EERNS4_11unique_lockINS4_5mutexEEEb + 260
13  .io.realm.realm-studio.WPJrcC       0x000000011283fdea _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 352
14  .io.realm.realm-studio.WPJrcC       0x0000000112826c9b _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 113
15  .io.realm.realm-studio.WPJrcC       0x000000011278bcab _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEPN2v87IsolateENS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedINS5_5LocalINS5_5ValueEEEEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_INSJ_INS5_8FunctionEEEEESO_NSF_INSP_ISQ_S10_EEEEEE + 127
16  .io.realm.realm-studio.WPJrcC       0x000000011278a0a6 _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEPN2v87IsolateENS5_5LocalINS5_6ObjectEEERNS0_9ArgumentsIS3_EE + 402
17  .io.realm.realm-studio.WPJrcC       0x00000001127893fb _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE + 333
18  .io.realm.realm-studio.WPJrcC       0x0000000112789df2 _ZN3Nan3impL23FunctionCallbackWrapperERKN2v820FunctionCallbackInfoINS1_5ValueEEE + 166
19  Electron Framework                  0x00000001069524a8 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 350504
20  Electron Framework                  0x000000010691bada _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 126810
21  Electron Framework                  0x000000010691b3a7 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 124967
22  Electron Framework                  0x0000000107262dce _ZN2v88internal6Parser31BuildIteratorCloseForCompletionEPNS0_8ZoneListIPNS0_9StatementEEEPNS0_8VariableEPNS0_10ExpressionENS0_12IteratorTypeE + 1450046!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
```

I'm afraid I'll be the one bringing the bad news here.
The files seem corrupted beyond the recoverable state.

Do you know what SDK and version was used to generate these files? Can you share more information on the app that produced these? What features does it use, how does the schema look like etc.?

Over the years we have fixed numerous bugs that could lead to file corruptions. Since these files were created with an outdated version of our library, there's not much more we can do to recover the lost data and as such I'll close this issue. Feel free to reopen, providing details on how we can systematically reproduce this with an updated version of our SDK.

**Closed as completed by kraenhansen** 2022-01-07 15:00 UTC
Labels: O-Community
