### ISSUE TITLE
Realm Studio object deletion

### ISSUE THREAD

**Issue by ianpward** [realm/realm-studio#769] opened 2018-04-11 19:24 UTC
Freshdesk Ticket ID: <a href='https://support.realm.io/helpdesk/tickets/411' target='_blank'>411</a> <br/> Freshdesk Ticket Agent: Ian Ward<br/>Freshdesk Ticket Agent Email: ian.ward@realm.io<br/>Ticket Priority: Low<br/>Freshdesk Ticket Description:<div dir="ltr">
<div>Realm Studio Version 1.20.0 (1.20.0.265)</div>
<div><br></div>
<div>On opening a realm, selecting an object, right-clicking and selecting 'Delete selected object', the object is correctly deleted.</div>
<div><br></div>
<div>However, if the list of objects is rearranged by clicking a reordering icon at the top beforehand, and then an object is deleted, the wrong object gets deleted. It appears that the object deleted is the one that was at the row position before the rearrangement of the list of objects. Deleting the wrong object is a major problem.</div>
<div><br></div>
<div>It would also be useful if the dialog for confirmation of a deletion also showed the key of the object to be deleted.</div>
</div> <br/>

**Comment by ianpward** [comment] 2018-07-10 03:17
@astigsen Assigning to you for server-side eng backlog prioritization

**Comment by kraenhansen** [comment] 2018-07-10 21:29
I am really sorry I didn't follow up on this. I must have forgotten to mark it as a duplicate of #788 which got closed by #832 27 days ago and released as Realm Studio 2.1.1 ... 27 days ago.

**Closed by kraenhansen** 2018-07-10 21:29 UTC
Labels: O:User PE/EE, P:1 Required

**Comment by ianpward** [comment] 2018-07-10 21:45
ya no problem - i thought it was fixed but couldn't be sure (I recall you posting on the forums about it) - thanks!
