### ISSUE TITLE
Unable to open encrypted realm from iOS Sim

### ISSUE THREAD

**Issue by elashpear** [realm/realm-studio#1320] opened 2020-07-31 00:16 UTC
**Describe the bug**
I was trying to use Realm Studio to debug an issue we were having when users were upgrading from one app version to the next.

**To Reproduce**
1. See how encryption key provided can open realm file from our (react native) app version 1.4. This version uses realm 2.29.2.
2. Try to open realm file from our app version 1.5. This version uses realm 6.0.2.

Use this encryption key: `0777085998a36a695d6bb9bfae88678a384d6c4b33d75cc94125ea7fe04cf4af0a6301249bc9fff763706bae0c0f1833fd139023829af66d7378374922017c98`

And try both realm files here:
[realm-error-repro.zip](https://github.com/realm/realm-studio/files/5004334/realm-error-repro.zip)

**Expected behavior**
A realm encrypted with the same key should be possible to open using realm studio. I can tell it's the same key because i dumped it from the application on both versions.

**Screenshots**
<img width="1792" alt="Screen Shot 2020-07-30 at 5 08 04 PM" src="https://user-images.githubusercontent.com/47397266/88986243-4055bc80-d287-11ea-9de9-0a73d3c4d1f7.png">

**Versions:**
 - OS: macOS 10.14.6
 - Studio Version 3.10.0
 - Realm Object Server: Not sure if applicable
- Environment generating realm file: iOS Simulator, iOS 13.3, React Native 0.61, Realm version 6.0.2

**Additional context**
This may be a dupe of https://github.com/realm/realm-studio/issues/865. That issue was closed by the author due to the "workaround" of decrypting the realm file before opening it. We don't really have that option as we are trying to inspect an encrypted realm generated by our application.

Stack trace:

```
Unable to open a realm at path '/Users/eliot/Dev/pear/reset-o-1.5/1.5-realm/store.20180508.realm': Unsupported Realm file format version (10) Path:Exception backtrace:
0 .io.realm.realm-studio.b3z8mu 0x0000000116ead271 _ZN5realm15InvalidDatabaseC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_ + 49
1 .io.realm.realm-studio.b3z8mu 0x0000000116ea5c1e _ZN5realm11SharedGroup7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_18SharedGroupOptionsE + 6430
2 .io.realm.realm-studio.b3z8mu 0x0000000116ba8a1c _ZN5realm11SharedGroup4openERNS_11ReplicationENS_18SharedGroupOptionsE + 236
3 .io.realm.realm-studio.b3z8mu 0x0000000116ba8403 _ZN5realm11SharedGroupC2ERNS_11ReplicationENS_18SharedGroupOptionsE + 1587
4 .io.realm.realm-studio.b3z8mu 0x0000000116b12ff1 _ZN5realm5Realm16open_with_configERKNS0_6ConfigERNSt3__110unique_ptrINS_11ReplicationENS4_14default_deleteIS6_EEEERNS5_INS_11SharedGroupENS7_ISB_EEEERNS5_INS_5GroupENS7_ISF_EEEEPS0_ + 1145
5 .io.realm.realm-studio.b3z8mu 0x0000000116b12926 _ZN5realm5RealmC2ENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEE + 278
6 .io.realm.realm-studio.b3z8mu 0x0000000116b1927e _ZZN5realm5Realm17make_shared_realmENS0_6ConfigENSt3__110shared_ptrINS_5_impl16RealmCoordinatorEEEEN19make_shared_enablerC2ES1_S6_ + 84
7 .io.realm.realm-studio.b3z8mu 0x0000000116b32da8 _ZNSt3__110shared_ptrIZN5realm5Realm17make_shared_realmENS2_6ConfigENS0_INS1_5_impl16RealmCoordinatorEEEE19make_shared_enablerE11make_sharedIJS3_S6_EEES8_DpOT_ + 136
8 .io.realm.realm-studio.b3z8mu 0x0000000116b2df7c _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EERNS4_11unique_lockINS4_5mutexEEEb + 260
9 .io.realm.realm-studio.b3z8mu 0x0000000116b2ddea _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigE + 352
10 .io.realm.realm-studio.b3z8mu 0x0000000116b14c9b _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 113
11 .io.realm.realm-studio.b3z8mu 0x0000000116a79cab _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEPN2v87IsolateENS_5Realm6ConfigEbONSt3__13mapINSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEENSB_ISH_NS0_9ProtectedINS5_5LocalINS5_5ValueEEEEENSA_4lessISH_EENSF_INSA_4pairIKSH_SM_EEEEEESO_NSF_INSP_ISQ_ST_EEEEEEONSB_ISH_NSI_INSJ_INS5_8FunctionEEEEESO_NSF_INSP_ISQ_S10_EEEEEE + 127
12 .io.realm.realm-studio.b3z8mu 0x0000000116a780a6 _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEPN2v87IsolateENS5_5LocalINS5_6ObjectEEERNS0_9ArgumentsIS3_EE + 402
13 .io.realm.realm-studio.b3z8mu 0x0000000116a773fb _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE9constructERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE + 333
14 .io.realm.realm-studio.b3z8mu 0x0000000116a77df2 _ZN3Nan3impL23FunctionCallbackWrapperERKN2v820FunctionCallbackInfoINS1_5ValueEEE + 166
15 Electron Framework 0x000000010c05f4a8 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 350504
16 Electron Framework 0x000000010c028ada _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 126810
17 Electron Framework 0x000000010c0283a7 _ZN2v88internallsERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEERKNS0_18BasicBlockProfilerE + 124967
18 Electron Framework 0x000000010c96fdce _ZN2v88internal6Parser31BuildIteratorCloseForCompletionEPNS0_8ZoneListIPNS0_9StatementEEEPNS0_8VariableEPNS0_10ExpressionENS0_12IteratorTypeE + 1450046
19 Electron Framework 0x000000010c8e1b20 _ZN2v88internal6Parser31BuildIteratorCloseForCompletionEPNS0_8ZoneListIPNS0_9StatementEEEPNS0_8VariableEPNS0_10ExpressionENS0_12IteratorTypeE + 867728.
```

**Comment by takameyer** [comment] 2021-12-15 10:54
Sorry for the late reply, somehow this fell through our radar.  Is this still an issue?  We will investigate this as soon as we can.

**Comment by elashpear** [comment] 2022-05-10 20:44
Yes, I am able to reproduce the issue in Realm Studio 3.10.1 (latest stable at this time of writing) with the repro files I uploaded above, so I think this is still a problem.

**Comment by kneth** [comment] 2022-09-01 16:02
We don't plan to work on bug fixes for Realm JavaScript pre-v10, and I am closing the issue. 

Please upgrade to latest version of Realm Studio. If the problem is still observed, please create a new issue.

**Closed** 2022-09-01 16:02 UTC
Labels: O-Community
