### ISSUE TITLE
White screen when opening a file

### ISSUE THREAD

**Issue by jersonpl** [realm/realm-studio#1547] opened 2022-11-24 09:20 UTC
Only a white screen is shown when opening a file

**To Reproduce**
1. Open realm studio 13
2. Clic Open Realm file

<img width="1440" alt="Screenshot 2022-11-24 at 10 18 49 AM" src="https://user-images.githubusercontent.com/39785621/203745116-9bbc0a08-06ec-416f-97cb-7260c5e05b42.png">

**Versions:**
 - OS: macOs Ventura 13.0
 - Realm Studio Version 13.0.0

**Additional context**
Version 12.0.0 works perfectly for me

**Comment by kneth** [comment] 2022-11-24 10:17
@jersonpl Thank you for reporting. We are working in finding a solution.

**Comment by kneth** [comment] 2022-11-24 21:04
@jersonpl We have identified the root cause, fixed it and re-release version 13.0.0. Please remove your current installation and reinstall.

I close the issue but don't hesitate to reopen if you still observe the issue.

**Closed as completed by kneth** 2022-11-24 21:04 UTC
Labels: O-Community
